import os

BASE_DIR = os.path.join(os.path.dirname(__file__), 'static')
LENGHT_JTI = 36
LENGHT_CONTENT = 100
LENGHT_TITLE = 20
LENGHT_USERNAME = 15
LENGHT_PASSWORD = 20
LENGHT_TOKEN = 32
LIKES_REQUIRED = 15
MAX_CONTENT_LENGTH = 1024
TIME_JWT = 5
TIME_QR = 300
